CREATE DATABASE QuanLyPhongMachTu;
USE QuanLyPhongMachTu;

CREATE TABLE CHUCVU
(
	MaCV int IDENTITY(1,1) primary key, 
	TenCV NVARCHAR(50) NOT NULL
);

CREATE TABLE CHUYENKHOA
(
	MaCK int IDENTITY(1,1) primary key, 
	TenCK NVARCHAR(50) NOT NULL
);

CREATE TABLE NHANVIEN
(
	MaNV int IDENTITY(1,1) Primary key,
	TenNV nvarchar(100) NOT NULL,
	GioiTinh Varchar(3) NOT NULL,
	NamSinh INT NOT NULL,
	SDT varchar(10) NOT NULL,
	MaCV int,
	MaCK int,
	CONSTRAINT fk_nv_cv FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV),
	CONSTRAINT fk_nv_ck FOREIGN KEY (MaCK) REFERENCES CHUYENKHOA(MaCK)
);

CREATE TABLE TAIKHOAN
(
	TenDangNhap VARCHAR(50) PRIMARY KEY,
	MatKhau VARCHAR(10) NOT NULL,
	MaNV INT UNIQUE,
	CONSTRAINT fk_tk_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE BENHNHAN
(
	MaBN INT IDENTITY(1,1) Primary Key,
	TenBN NVARCHAR(100) NOT NULL,
	CCCD VARCHAR(12) UNIQUE,
	GioiTinh VARCHAR(3) NOT NULL,
	NgaySinh Date NOT NULL,
	DiaChi NVARCHAR(255),
	SDT VARCHAR(10) NOT NULL,
	Email VARCHAR(100)
);


CREATE TABLE PHIEUKHAM
(
	MaPK INT IDENTITY(1,1) PRIMARY KEY,
	MaNV INT,
	MaBN INT,
	NgayKham DATE NOT NULL,
	CONSTRAINT fk_pk_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	CONSTRAINT fk_pk_bn FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN)
);

CREATE TABLE DONVITINH
(
	MaDVT INT IDENTITY(1,1) PRIMARY KEY,
	TenDVT NVARCHAR(20) NOT NULL
);

CREATE TABLE CACHDUNG
(
	MaCachDung INT IDENTITY(1,1) PRIMARY KEY,
	MoTaCachDung NVARCHAR(255) NOT NULL
);

CREATE TABLE THUOC
(
	MaThuoc INT IDENTITY(1,1) PRIMARY KEY,
	TenThuoc NVARCHAR(255) NOT NULL,
	DonGiaBan DECIMAL(18,2) NOT NULL,
	SoLuongTon  INT DEFAULT 0,
	MaCachDung INT,
	MaDVT INT,
	CONSTRAINT fk_t_cd FOREIGN KEY (MaCachDung) REFERENCES CACHDUNG(MaCachDung),
	CONSTRAINT fk_t_dvt FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);

CREATE TABLE CT_PHIEUKHAM
(
	MaPK INT,
	MaThuoc INT,
	SoLuongThuoc INT NOT NULL,
	DonGiaBan DECIMAL(18,2) NOT NULL,
	ThanhTien DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT pk_ctpk PRIMARY KEY(MaPK, MaThuoc),
	CONSTRAINT fk_ctpk_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK),
	CONSTRAINT fk_ctpk_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE PHIEUNHAPTHUOC
(
	MaPN INT IDENTITY(1,1) PRIMARY KEY,
	NgayNhap DATE NOT NULL,
	TongTienNhap DECIMAL(18,2) DEFAULT 0,
);

CREATE TABLE CT_PHIEUNHAPTHUOC
(
	MaPN INT,
	MaThuoc INT, 
	DonGiaNhap DECIMAL(18,2) NOT NULL,
	SoLuong INT NOT NULL,
	ThanhTien DECIMAL(18,2) NOT NULL,
	CONSTRAINT pk_pnt PRIMARY KEY(MaPN, MaThuoc),
	CONSTRAINT fk_ctpnt_pn FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPTHUOC(MaPN),
	CONSTRAINT fk_ctpnt_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE LOAIBENH
(
	MaLoaiBenh INT IDENTITY(1,1) PRIMARY KEY,
	TenBenh NVARCHAR(255) NOT NULL
);

CREATE TABLE CT_LOAIBENH
(
	MaPK INT, 
	MaLoaiBenh INT,
	TrieuChung NVARCHAR(255),
	GhiChu NVARCHAR(255),
	CONSTRAINT pk_ctlb PRIMARY KEY(MaPK, MaLoaiBenh),
	CONSTRAINT fk_ctlb_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK),
	CONSTRAINT fk_ctlb_b FOREIGN KEY (MaLoaiBenh) REFERENCES LOAIBENH(MaLoaiBenh)
);

CREATE TABLE HOADON
(
	MaHD INT IDENTITY(1,1) PRIMARY KEY,
	MaPK INT,
	NgayLap DATETIME,
	TongTienThuoc DECIMAL(18,2) NOT NULL,
	TienKham DECIMAL(18,2) NOT NULL,
	TongTien DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT fk_hd_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK)
);

CREATE TABLE BCDOANHTHU
(
	Thang INT,
	Nam INT,
	TongDoanhThu DECIMAL(18,2) NOT NULL,
	TongSoBenhNhan INT NOT NULL,
	CONSTRAINT pk_bcdt PRIMARY KEY (Thang, Nam)
);

CREATE TABLE CT_BCDOANHTHU
(
	Ngay INT,
	Thang INT, 
	Nam INT,
	SoBenhNhan INT NOT NULL,
	DoanhThu DECIMAL(18,2) DEFAULT 0,
	TyLe DECIMAL(3,2) NOT NULL,
	CONSTRAINT pk_ctbcdt PRIMARY KEY (Ngay, Thang, Nam),
	CONSTRAINT fk_ctbcdt_bcdt FOREIGN KEY (Thang, Nam) REFERENCES BCDOANHTHU(Thang, Nam)
);

CREATE TABLE BCSUDUNGTHUOC
(
	Thang INT,
	Nam INT,
	MaThuoc INT,
	SoLanDung INT NOT NULL,
	SoLuongDung INT NOT NULL,
	SoLuongNhap INT NOT NULL,
	CONSTRAINT pk_bcsdt PRIMARY KEY(Thang, Nam, MaThuoc),
	CONSTRAINT fk_bcsdt_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE THAMSO
(
	TenThamSo NVARCHAR(100) PRIMARY KEY,
	GiaTri DECIMAL(18,2) NOT NULL
);

