CREATE DATABASE QuanLyPhongMachTu;
USE QuanLyPhongMachTu;

CREATE TABLE CHUCVU
(
	MaCV int IDENTITY(1,1) primary key, 
	TenCV NVARCHAR(50) NOT NULL
);

CREATE TABLE CHUYENKHOA
(
	MaCK int IDENTITY(1,1) primary key, 
	TenCK NVARCHAR(50) NOT NULL
);

CREATE TABLE NHANVIEN
(
	MaNV int IDENTITY(1,1) Primary key,
	TenNV nvarchar(100) NOT NULL,
	GioiTinh Varchar(3) NOT NULL,
	NamSinh INT NOT NULL,
	SDT varchar(10) NOT NULL,
	MaCV int,
	MaCK int,
	CONSTRAINT fk_nv_cv FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV),
	CONSTRAINT fk_nv_ck FOREIGN KEY (MaCK) REFERENCES CHUYENKHOA(MaCK)
);

CREATE TABLE TAIKHOAN
(
	TenDangNhap VARCHAR(50) PRIMARY KEY,
	MatKhau VARCHAR(10) NOT NULL,
	MaNV INT UNIQUE,
	CONSTRAINT fk_tk_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE BENHNHAN
(
	MaBN INT IDENTITY(1,1) Primary Key,
	TenBN NVARCHAR(100) NOT NULL,
	CCCD VARCHAR(12) UNIQUE,
	GioiTinh VARCHAR(3) NOT NULL,
	NgaySinh Date NOT NULL,
	DiaChi NVARCHAR(255),
	SDT VARCHAR(10) NOT NULL,
	Email VARCHAR(100)
);


CREATE TABLE PHIEUKHAM
(
	MaPK INT IDENTITY(1,1) PRIMARY KEY,
	MaNV INT,
	MaBN INT,
	NgayKham DATE NOT NULL,
	CONSTRAINT fk_pk_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	CONSTRAINT fk_pk_bn FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN)
);

CREATE TABLE DONVITINH
(
	MaDVT INT IDENTITY(1,1) PRIMARY KEY,
	TenDVT NVARCHAR(20) NOT NULL
);

CREATE TABLE CACHDUNG
(
	MaCachDung INT IDENTITY(1,1) PRIMARY KEY,
	MoTaCachDung NVARCHAR(255) NOT NULL
);

CREATE TABLE THUOC
(
	MaThuoc INT IDENTITY(1,1) PRIMARY KEY,
	TenThuoc NVARCHAR(255) NOT NULL,
	DonGiaBan DECIMAL(18,2) NOT NULL,
	SoLuongTon  INT DEFAULT 0,
	MaCachDung INT,
	MaDVT INT,
	CONSTRAINT fk_t_cd FOREIGN KEY (MaCachDung) REFERENCES CACHDUNG(MaCachDung),
	CONSTRAINT fk_t_dvt FOREIGN KEY (MaDVT) REFERENCES DONVITINH(MaDVT)
);

CREATE TABLE CT_PHIEUKHAM
(
	MaPK INT,
	MaThuoc INT,
	SoLuongThuoc INT NOT NULL,
	DonGiaBan DECIMAL(18,2) NOT NULL,
	ThanhTien DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT pk_ctpk PRIMARY KEY(MaPK, MaThuoc),
	CONSTRAINT fk_ctpk_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK),
	CONSTRAINT fk_ctpk_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE PHIEUNHAPTHUOC
(
	MaPN INT IDENTITY(1,1) PRIMARY KEY,
	NgayNhap DATE NOT NULL,
	TongTienNhap DECIMAL(18,2) DEFAULT 0,
);

CREATE TABLE CT_PHIEUNHAPTHUOC
(
	MaPN INT,
	MaThuoc INT, 
	DonGiaNhap DECIMAL(18,2) NOT NULL,
	SoLuong INT NOT NULL,
	ThanhTien DECIMAL(18,2) NOT NULL,
	CONSTRAINT pk_pnt PRIMARY KEY(MaPN, MaThuoc),
	CONSTRAINT fk_ctpnt_pn FOREIGN KEY (MaPN) REFERENCES PHIEUNHAPTHUOC(MaPN),
	CONSTRAINT fk_ctpnt_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE LOAIBENH
(
	MaLoaiBenh INT IDENTITY(1,1) PRIMARY KEY,
	TenBenh NVARCHAR(255) NOT NULL
);

CREATE TABLE CT_LOAIBENH
(
	MaPK INT, 
	MaLoaiBenh INT,
	TrieuChung NVARCHAR(255),
	GhiChu NVARCHAR(255),
	CONSTRAINT pk_ctlb PRIMARY KEY(MaPK, MaLoaiBenh),
	CONSTRAINT fk_ctlb_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK),
	CONSTRAINT fk_ctlb_b FOREIGN KEY (MaLoaiBenh) REFERENCES LOAIBENH(MaLoaiBenh)
);

CREATE TABLE HOADON
(
	MaHD INT IDENTITY(1,1) PRIMARY KEY,
	MaPK INT,
	NgayLap DATETIME,
	TongTienThuoc DECIMAL(18,2) NOT NULL,
	TienKham DECIMAL(18,2) NOT NULL,
	TongTien DECIMAL(18,2) DEFAULT 0,
	CONSTRAINT fk_hd_pk FOREIGN KEY (MaPK) REFERENCES PHIEUKHAM(MaPK)
);

CREATE TABLE BCDOANHTHU
(
	Thang INT,
	Nam INT,
	TongDoanhThu DECIMAL(18,2) NOT NULL,
	TongSoBenhNhan INT NOT NULL,
	CONSTRAINT pk_bcdt PRIMARY KEY (Thang, Nam)
);

CREATE TABLE CT_BCDOANHTHU
(
	Ngay INT,
	Thang INT, 
	Nam INT,
	SoBenhNhan INT NOT NULL,
	DoanhThu DECIMAL(18,2) DEFAULT 0,
	TyLe DECIMAL(3,2) NOT NULL,
	CONSTRAINT pk_ctbcdt PRIMARY KEY (Ngay, Thang, Nam),
	CONSTRAINT fk_ctbcdt_bcdt FOREIGN KEY (Thang, Nam) REFERENCES BCDOANHTHU(Thang, Nam)
);

CREATE TABLE BCSUDUNGTHUOC
(
	Thang INT,
	Nam INT,
	MaThuoc INT,
	SoLanDung INT NOT NULL,
	SoLuongDung INT NOT NULL,
	SoLuongNhap INT NOT NULL,
	CONSTRAINT pk_bcsdt PRIMARY KEY(Thang, Nam, MaThuoc),
	CONSTRAINT fk_bcsdt_t FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);

CREATE TABLE THAMSO
(
	TenThamSo NVARCHAR(100) PRIMARY KEY,
	GiaTri DECIMAL(18,2) NOT NULL
);


--1. CHUCVU
INSERT INTO CHUCVU (TenCV) VALUES
(N'Bác sĩ'),
(N'Lễ tân'),
(N'Admin');

--2. CHUYENKHOA
INSERT INTO CHUYENKHOA (TenCK) VALUES
(N'Nội tổng quát'),
(N'Tim mạch'),
(N'Da liễu'),
(N'Tai mũi họng'),
(N'Nhi khoa');


--3. NHANVIEN
INSERT INTO NHANVIEN (TenNV, GioiTinh, NamSinh, SDT, MaCV, MaCK) VALUES
(N'Trần Triệu Dân', 'Nam',  2005, '0901234561', 1, 1), 
(N'Nguyễn Vũ Thùy Trâm', 'Nữ',  2005, '0901234562', 1, 2), 
(N'Dương Thanh Hiếu', 'Nam',  2005, '0901234563', 1, 5), 
(N'Nguyễn Thị Nhâm', 'Nữ',  2005, '0901234564', 1, 3), 
(N'Nguyễn Trần Phương Vy', 'Nữ',  2005, '0901234565', 1, 4),
(N'Hoàng Gia Huy', 'Nam', 2000, '0901234565', 3, NULL),
(N'Phạm Thị Dung', 'Nữ', 2003, '0901234564', 2, NULL);


--4. TAIKHOAN
INSERT INTO TAIKHOAN (TenDangNhap, MatKhau, MaNV) VALUES
('admin', '123', 6),
('bacsi1', '123', 1),
('bacsi2', '123', 2),
('letan1', '123', 7);

--5. BENHNHAN
INSERT INTO BENHNHAN (TenBN, CCCD, GioiTinh, NgaySinh, DiaChi, SDT, Email) VALUES
(N'Nguyễn Thị Mai', '001234567890', 'Nữ', '2000-05-12', N'Thủ Đức', '0911111111', 'mai@gmail.com'),
(N'Trần Văn Nam', '001234567891', 'Nam', '1998-03-15', N'Quận 9', '0911111112', 'nam@gmail.com'),
(N'Lê Thị Hoa', '001234567892', 'Nữ', '2001-09-20', N'Dĩ An', '0911111113', 'hoa@gmail.com'),
(N'Phạm Văn Long', '001234567893', 'Nam', '1995-12-01', N'Bình Thạnh', '0911111114', 'long@gmail.com'),
(N'Đỗ Minh Anh', '001234567894', 'Nữ', '2002-07-25', N'Thủ Đức', '0911111115', 'anh@gmail.com');


--6. LOAIBENH (loại bệnh)
INSERT INTO LOAIBENH (TenBenh) VALUES
(N'Cảm cúm'),
(N'Sốt'),
(N'Đau dạ dày'),
(N'Dị ứng'),
(N'Viêm họng'); 

--7. CACHDUNG
INSERT INTO CACHDUNG (MoTaCachDung) VALUES
(N'Uống sau ăn'),
(N'Uống trước ăn'),
(N'Ngày 2 lần'),
(N'Ngày 3 lần'),
(N'Khi cần');

--8. DONVITINH
INSERT INTO DONVITINH (TenDVT) VALUES
(N'Viên'),
(N'Chai'),
(N'Gói'),
(N'Ống'),
(N'Tuýp');


--9. THUOC
INSERT INTO THUOC (TenThuoc, DonGiaBan, SoLuongTon, MaCachDung, MaDVT) VALUES
(N'Paracetamol', 5000, 100, 1, 1),
(N'Amoxicillin', 10000, 80, 3, 1),
(N'Vitamin C', 3000, 200, 5, 1),
(N'Efferalgan', 7000, 120, 2, 1),
(N'Sirô ho', 25000, 50, 4, 2);


--10.PHIEUKHAM
INSERT INTO PHIEUKHAM(MaNV, MaBN, NgayKham) VALUES
(1, 1, '2026-03-10'),
(2, 2, '2026-04-10'),
(3, 3, '2026-05-11'),
(1, 4, '2026-05-11'),
(2, 5, '2026-10-12');

--11. CT_PHIEUKHAM
INSERT INTO CT_PHIEUKHAM (MaPK, MaThuoc, SoLuongThuoc, DonGiaBan, ThanhTien) VALUES
(1, 1, 2, 5000, 10000),
(1, 3, 1, 3000, 3000),
(2, 2, 1, 10000, 10000),
(3, 5, 1, 25000, 25000),
(4, 4, 2, 7000, 14000),
(5, 1, 1, 5000, 5000);


--12. HOADON
INSERT INTO HOADON (MaPK, NgayLap, TongTienThuoc, TienKham, TongTien) VALUES
(1, '2026-03-10', 13000, 30000, 43000),
(2, '2026-04-10', 10000, 30000, 40000),
(3, '2026-05-11', 15000, 30000, 45000),
(4, '2026-05-11', 14000, 30000, 44000),
(5, '2026-10-12', 25000, 30000, 55000);
